language: C
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - lcov
      - python-numpy
      - python-scipy
install:
  - sudo gem install coveralls-lcov       
before_install:
  - sudo ldconfig 
script:
  - make COV=1 test
  - make COV=1 run-test
  - cd python/
  - sudo python setup.py install > /dev/null
  - python -m unittest -v test_superscs
  - cd ..
  - sudo make clean
  - make profile-run PF=1 PROBLEM_YAML_FILE='\"tests/c/data/test-5.yml\"' -s
  - make COV=1 cov
cache:  
  apt: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
