language: C
sudo: required
dist: trusty
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - lcov
      - python-numpy
      - python-scipy
install:
  - sudo gem install coveralls-lcov       
before_install:
  - sudo ldconfig 
script:
  # the following line is because travis CI can't locate 
  # clang under sudo.
  - export CC=`which $CC` 
  - make COV=1 test
  - make COV=1 run-test
  - cd python/
  - sudo python setup.py install
  - python -m unittest -v test_superscs
  - cd ..
  - sudo make clean
  - make profile-run PF=1 PROBLEM_YAML_FILE='\"tests/c/data/test-5.yml\"' -s
  # Run coverage only for gcc
  - if [[ $CC = *"gcc"* ]]; then; make COV=1 cov; fi
cache:  
  apt: true
after_success:
  - f [[ $CC = *"gcc"* ]]; then; bash <(curl -s https://codecov.io/bash); fi
