language: C
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - lcov
      - python-numpy
      - python-scipy
install:
  - sudo gem install coveralls-lcov       
before_install:
  - sudo ldconfig 
  - make COV=1
script:
  - make COV=1 test
  - make COV=1 run-test
  - cd python/
  - sudo python setup.py install
  - python test_scs_sdp.py
  - cd ..
cache:  
  apt: true
after_success:
  - make cov COV=1
  - bash <(curl -s https://codecov.io/bash)
