language: C
sudo: required
matrix:
    include:
        - os: linux
          dist: trusty
          compiler: gcc
          env: SCS_RUN_COV=1
        - os: linux
          dist: trusty
          compiler: clang
          env: SCS_RUN_COV=1
        - os: osx
          env: SCS_RUN_CON=0
addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - lcov
      - python-numpy
      - python-scipy
install:
  - ./.travis/scs_install.sh
before_install:
  - ./.travis/scs_before_install.sh
script:     
  - ./.travis/scs_script.sh
after_success:  
  - ./.travis/scs_after_success.sh
cache:  
  apt: true